# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7484e88e8b328221180c78a456e44eacbb386fdab61b4594ef337ea51e6d25be6904cc67dc9ea080153e40d059f424ea44bc9fabeef3c5058c201df941064e4e

test:
  secret_key_base: d42eb86a913282a13a45daefa79b7153fdc4f794525cd703e4b4b8e398d7bfdb10bbc188ac3d42c93c5f839c51474e228ce3cc7e6024de5ff35656ccd337ff58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
